export type LeadStatus = string; // Use string for now, as Supabase uses character varying
export type LeadSource = 'website' | 'referral' | 'social' | 'email' | 'phone' | 'other';

export interface Lead {
  id: string;
  firstName: string;
  lastName: string;
  email?: string;
  phone?: string;
  gender?: string;
  status?: LeadStatus;
  source?: string;
  notes?: string;
  ai_notes?: string;
  ai_sentiment?: number;
  created_at?: string;
  updated_at?: string;
  rating?: number;
  location?: string;
  property_interest?: string;
  investment_type?: string;
  budget_range?: string;
  preferred_areas?: string[];
  priority?: string;
  crm_id?: string;
}

// Form data type for creating/updating leads
export type LeadFormData = Omit<Lead, 'id' | 'created_at' | 'updated_at'>; // id, created_at, updated_at are generated by backend 